### ISSUE TITLE
script error set multizone 

### ISSUE THREAD

**Issue by infohannes** [Barma-lej/halandroid#42]
Hello Barma-lej

at first thanks for your great work!
Every think is working fine without setup from my multizone
If I select a zone number, then I get this script error: script/mower_setzone 
can only concatenate str(not "int") to str...
 - service: landroid_cloud.setzone
        data:
          id: "{{ state_attr('sensor.landroid_mower_status','id') }}"
          zone: "{{ states('input_select.mower_zone') | int(0) }}"
What I have understand here, it must be a str, but I'm to stupid to change it...

Can you or any other person here help me?

I use Home Assistant 2022.4.0

_Originally posted by @infohannes in https://github.com/Barma-lej/halandroid/issues/39#issuecomment-1092874051_

**Comment by Barma-lej** [comment]
Can you publish full error text?

**Comment by Barma-lej** [comment]
Try to remove ` | int(0)` in line:
```
zone: "{{ states('input_select.mower_zone') | int(0) }}"
```
e.g.
```
zone: "{{ states('input_select.mower_zone') }}"
```

**Comment by infohannes** [comment]
Hey Barmalej,

thanks for feedback. 
I've already tried that, unfortunately it doesn't solve this problem...
Inside the home assitant develoment tools. It's working, when I insert for the zone '0' ; '1' 2,3 
service: landroid_cloud.setzone
data:
  id: '{{ state_attr(''sensor.landroid_mower_status'',''id'') }}'
  zone: '0'

Inside the template editor its looking good...
![Screenshot_1](https://user-images.githubusercontent.com/69587436/162494739-5abf8345-2c0f-4cab-a451-87352274e3c2.png)

But If I call it, see here
  
![IMG_7379](https://user-images.githubusercontent.com/69587436/162493830-1da5a7e2-a7fc-4f88-b8f1-17cb3ddcd8f3.PNG)

**Comment by infohannes** [comment]
I have really no Idee

**Comment by Barma-lej** [comment]
It's fixed by https://github.com/MTrab/landroid_cloud/issues/98
You should update integration landroid_cloud

**Comment by infohannes** [comment]
barmalej,
thank you for your feedback.
Now I've updated my Landroid Cloud to version 1.8.5 (these should contain your bug fix) and restart Home Assistant, but it's still the same error. I mean, in this official version it is not included. It may be?
![Screenshot_2](https://user-images.githubusercontent.com/69587436/162626595-5de07068-1f12-4085-ae21-05606a7ec105.png)
 best regards 
 infohannes

**Comment by infohannes** [comment]
logging too...

Logger: homeassistant.components.script.mower_setzone
Source: custom_components/landroid_cloud/__init__.py:351
Integration: Skript (documentation, issues)
First occurred: 20:41:12 (4 occurrences)
Last logged: 20:45:53

Mower set mowing zone: Error executing script. Unexpected error for call_service at pos 3: can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 379, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 582, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1634, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1671, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/landroid_cloud/__init__.py", line 351, in handle_setzone
    cli.setZone(call.data["zone"])
  File "/usr/local/lib/python3.9/site-packages/pyworxcloud/__init__.py", line 327, in setZone
    msg = '{"mz":' + zone + '}'
TypeError: can only concatenate str (not "int") to str

**Comment by infohannes** [comment]
@Barma-lej 
now is fixed with your great support
Thank you 

![grafik](https://user-images.githubusercontent.com/69587436/163873815-2124644b-ab3c-4065-8a8a-52dfbe2481ec.png)
